### ISSUE TITLE
ReST API support

### ISSUE THREAD

**Issue by nrshrivatsan** [coreos/quay-docs#36]
Quay is a very useful tool.

However it would be very pleasant to have ReST APIs - Specifically HTTP/1.1 GET for teams/repositories/container-commits etc.

Is this technically feasible?

**Comment by josephschorr** [comment]
Hi Shrivatsan,

We actually have a REST API in pre-release that can be found here: http://docs.quay.io/api/. We don't currently link to it from the docs front page as it may change until such time as we formally release it.
