### ISSUE TITLE
Quay Docs are very ADD-focused; best practices are to use COPY.

### ISSUE THREAD

**Issue by optimality** [coreos/quay-docs#9]
[Dockerfile best practices](https://docs.docker.com/articles/dockerfile_best-practices/#add-or-copy) say to prefer using COPY, but the Quay [Repeatable Deployments](http://docs.quay.io/solution/repeatable-deployments.html) page uses ADD exclusively, despite needing none of the special functionality of ADD.

Should probably replace those with COPY.

**Comment by jzelinskie** [comment]
Lots of our articles were written before `COPY` existed. I'll update them.

Thanks!
